

include(LibFindMacros)

# Use pkg-config to get hints about paths
libfind_pkg_check_modules(RESIP_PKGCONF dum)

# Include dir
find_path(RESIP_INCLUDE_DIR
  NAMES resip/stack/SipMessage.hxx
  PATHS ${RESIP_PKGCONF_INCLUDE_DIRS}
)

if (WIN32)
		FIND_LIBRARY(RESIP_DUM_LIBRARY_DEBUG NAMES dum-sgd dum_sgd)
		FIND_LIBRARY(RESIP_RESIP_LIBRARY_DEBUG NAMES resiprocate-sgd resiprocate_sgd)
		FIND_LIBRARY(RESIP_RUTIL_LIBRARY_DEBUG NAMES rutil-sgd rutil_sgd)
		FIND_LIBRARY(RESIP_ARES_LIBRARY_DEBUG NAMES ares-sgd ares_sgd)
		FIND_LIBRARY(RESIP_DUM_LIBRARY_RELEASE NAMES dum-s dum_s)
		FIND_LIBRARY(RESIP_RESIP_LIBRARY_RELEASE NAMES resiprocate-s resiprocate_s)
		FIND_LIBRARY(RESIP_RUTIL_LIBRARY_RELEASE NAMES rutil-s rutil_s)
		FIND_LIBRARY(RESIP_ARES_LIBRARY_RELEASE NAMES ares-s ares_s)
		
		SET(RESIP_DUM_LIBRARY debug ${RESIP_DUM_LIBRARY_DEBUG} optimized ${RESIP_DUM_LIBRARY_RELEASE})
		SET(RESIP_RESIP_LIBRARY debug ${RESIP_RESIP_LIBRARY_DEBUG} optimized ${RESIP_RESIP_LIBRARY_RELEASE})
		SET(RESIP_RUTIL_LIBRARY debug ${RESIP_RUTIL_LIBRARY_DEBUG} optimized ${RESIP_RUTIL_LIBRARY_RELEASE})
		SET(RESIP_ARES_LIBRARY debug ${RESIP_ARES_LIBRARY_DEBUG} optimized ${RESIP_ARES_LIBRARY_RELEASE})
		SET(RESIP_WINDOWS_DEPS_LIBRARY ws2_32.lib Iphlpapi.lib)
		#MESSAGE(STATUS ${RESIP_DUM_LIBRARY})
else()

FIND_LIBRARY(RESIP_DUM_LIBRARY NAMES dum libdum PATH ${RESIP_PKGCONF_LIBRARY_DIRS})
FIND_LIBRARY(RESIP_RESIP_LIBRARY NAMES resip resiprocate libresip libresiprocate PATH ${RESIP_PKGCONF_LIBRARY_DIRS})
FIND_LIBRARY(RESIP_RUTIL_LIBRARY NAMES rutil librutil  PATH ${RESIP_PKGCONF_LIBRARY_DIRS})
FIND_LIBRARY(RESIP_POPT_LIBRARY NAMES popt libpopt PATH ${RESIP_PKGCONF_LIBRARY_DIRS})
FIND_LIBRARY(RESIP_ARES_LIBRARY NAMES ares libares PATH ${RESIP_PKGCONF_LIBRARY_DIRS})
SET (RESIP_RT_LIBRARY "rt")
endif()

# Set the include dir variables and the libraries and let libfind_process do the rest.
# NOTE: Singular variables for this library, plural for libraries this this lib depends on.

if (WIN32)
	set(RESIP_PROCESS_LIBS RESIP_DUM_LIBRARY RESIP_RESIP_LIBRARY RESIP_RUTIL_LIBRARY RESIP_ARES_LIBRARY RESIP_WINDOWS_DEPS_LIBRARY)
else()
if (EXISTS RESIP_POPT_LIBRARY)
	SET(RESIP_PROCESS_LIBS RESIP_DUM_LIBRARY RESIP_RESIP_LIBRARY RESIP_RUTIL_LIBRARY RESIP_POPT_LIBRARY RESIP_ARES_LIBRARY RESIP_RT_LIBRARY)
else (EXISTS RESIP_POPT_LIBRARY)
	set(RESIP_PROCESS_LIBS RESIP_DUM_LIBRARY RESIP_RESIP_LIBRARY RESIP_RUTIL_LIBRARY RESIP_ARES_LIBRARY RESIP_RT_LIBRARY)
endif(EXISTS RESIP_POPT_LIBRARY)
endif()
set(RESIP_PROCESS_INCLUDES RESIP_INCLUDE_DIR)
libfind_process(RESIP)
