# -lmp4av -lmp4v2
FIND_PATH(MPEG4IP_INCLUDE_DIR mpeg4ip.h /usr/include /usr/local/include /opt/include /usr/include/mpeg4ip /usr/local/include/mpeg4ip)
FIND_LIBRARY(MPEG4IP_MP4AV_LIBRARY mp4av PATH /usr/lib /usr/local/lib /opt/lib)
FIND_LIBRARY(MPEG4IP_MP4V2_LIBRARY mp4v2 PATH /usr/lib /usr/local/lib /opt/lib)

IF (MPEG4IP_INCLUDE_DIR AND MPEG4IP_MP4AV_LIBRARY AND MPEG4IP_MP4V2_LIBRARY)
   SET(MPEG4IP_FOUND TRUE)
   SET(MPEG4IP_LIBRARY ${MPEG4IP_MP4AV_LIBRARY} ${MPEG4IP_MP4V2_LIBRARY})
ENDIF (MPEG4IP_INCLUDE_DIR AND MPEG4IP_MP4AV_LIBRARY AND MPEG4IP_MP4V2_LIBRARY)

IF (MPEG4IP_FOUND)
   IF (NOT MPEG4IP_FIND_QUIETLY)
      MESSAGE(STATUS "Found MPEG4IP: ${MPEG4IP_LIBRARY}")
   ENDIF (NOT MPEG4IP_FIND_QUIETLY)
ELSE (MPEG4IP_FOUND)
   IF (MPEG4IP_FIND_REQUIRED)
      MESSAGE(FATAL_ERROR "Could not find MPEG4IP")
   ENDIF (MPEG4IP_FIND_REQUIRED)
ENDIF (MPEG4IP_FOUND)
