
FIND_PATH(LIVEMEDIA_INCLUDE_DIR liveMedia.hh /usr/include /usr/local/include /opt/include /usr/local/include/liveMedia /usr/include/liveMedia /opt/include/liveMedia)

FIND_LIBRARY(LM_BASICUSAGEENVIRONMENT_LIBRARY NAMES BasicUsageEnvironment basicusageenvironment PATH /usr/lib /usr/local/lib /opt/lib)
FIND_LIBRARY(LM_USAGEENVIRONMENT_LIBRARY NAMES UsageEnvironment usageenvironment PATH /usr/lib /usr/local/lib /opt/lib)
FIND_LIBRARY(LM_GROUPSOCK_LIBRARY NAMES Groupsock groupsock PATH /usr/lib /usr/local/lib /opt/lib)
FIND_LIBRARY(LM_LIVEMEDIA_LIBRARY NAMES liveMedia LiveMedia PATH /usr/lib /usr/local/lib /opt/lib)

IF (LIVEMEDIA_INCLUDE_DIR AND LM_BASICUSAGEENVIRONMENT_LIBRARY AND LM_USAGEENVIRONMENT_LIBRARY AND LM_GROUPSOCK_LIBRARY AND LM_LIVEMEDIA_LIBRARY)
   SET(LIVEMEDIA_FOUND TRUE)
   SET(LIVEMEDIA_LIBRARY ${LM_LIVEMEDIA_LIBRARY} ${LM_BASICUSAGEENVIRONMENT_LIBRARY} ${LM_USAGEENVIRONMENT_LIBRARY} ${LM_GROUPSOCK_LIBRARY} )
ENDIF (LIVEMEDIA_INCLUDE_DIR AND LM_BASICUSAGEENVIRONMENT_LIBRARY AND LM_USAGEENVIRONMENT_LIBRARY AND LM_GROUPSOCK_LIBRARY AND LM_LIVEMEDIA_LIBRARY)


IF (LIVEMEDIA_FOUND)
   IF (NOT LiveMedia_FIND_QUIETLY)
      MESSAGE(STATUS "Found LiveMedia: ${LIVEMEDIA_LIBRARY}")
   ENDIF (NOT LiveMedia_FIND_QUIETLY)
ELSE (LIVEMEDIA_FOUND)
   IF (LiveMedia_FIND_REQUIRED)
      MESSAGE(FATAL_ERROR "Could not find LiveMedia")
   ENDIF (LiveMedia_FIND_REQUIRED)
ENDIF (LIVEMEDIA_FOUND)